RecordCollection/Models/Artist.cs
using System.Collections.Generic;

namespace RecordCollection.Models
{
  public class Artist
  {
    public Artist()
    {
      this.AlbumsGenres = new HashSet<AlbumArtistGenre>();
    }
    
    public int ArtistId { get; set; }
    public string Name { get; set; }
    public string ImageUrl { get; set; }
    public virtual ICollection<AlbumArtistGenre> AlbumsGenres { get; set; }
  }
}

RecordCollection/Controllers/AlbumsController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using System.Collections.Generic;
using System.Linq;
using System.Text.RegularExpressions;
using RecordCollection.Models;

namespace RecordCollection.Controllers
{
  public class AlbumsController : Controller
  {
  
    private readonly RecordCollectionContext _db;

    public AlbumsController(RecordCollectionContext db)
    {
      _db = db;
    }

    public ActionResult Index(string name)
    {
      IQueryable<Album> albumQuery = _db.Albums;
      if (!string.IsNullOrEmpty(name))
      {
        Regex search = new Regex(name, RegexOptions.IgnoreCase);
        albumQuery = albumQuery.Where(albums => search.IsMatch(albums.Name));
      }
      IEnumerable<Album> albumList = albumQuery.ToList().OrderBy(albums => albums.Name);
      return View(albumList);
    }

    public ActionResult Create()
    {
      ViewBag.ArtistId = new SelectList(_db.Artists, "ArtistId", "Name");
      ViewBag.GenreId = new SelectList(_db.Genres, "GenreId", "Name");
      return View();
    }

    [HttpPost]
    public ActionResult Create(Album albums, int ArtistId, int GenreId)
    {
      _db.Albums.Add(albums);
      if (ArtistId != 0)
      {
        _db.AlbumArtistGenre.Add(new AlbumArtistGenre() { ArtistId = ArtistId, AlbumId = albums.AlbumId });
      }
      if (GenreId != 0)
      {
        _db.AlbumArtistGenre.Add(new AlbumArtistGenre() { GenreId = GenreId, AlbumId = albums.AlbumId });
      }
      _db.SaveChanges();
      return RedirectToAction("Details", new { id = albums.AlbumId });
    }

    public ActionResult Details(int id)
    {
      Album album = _db.Albums
        .Include(albums => albums.ArtistsGenres)
        .ThenInclude(join => join.Artist)
        .Include(albums => albums.ArtistsGenres)
        .ThenInclude(join => join.Genre)
        .First(albums => albums.AlbumId == id);
      ViewBag.ArtistCount = _db.AlbumArtistGenre.Where(join => join.AlbumId == id).Where(join => join.ArtistId != null).Count();
      ViewBag.GenreCount = _db.AlbumArtistGenre.Where(join => join.AlbumId == id).Where(join => join.GenreId != null).Count();
      return View(album);  
    }

    public ActionResult Edit(int id)
    {
      Album model = _db.Albums.FirstOrDefault(album => album.AlbumId == id);
      return View(model);
    }

    [HttpPost]
    public ActionResult Edit(Album album)
    {
      _db.Entry(album).State = EntityState.Modified;
      _db.SaveChanges();
      return RedirectToAction("Details", new { id = album.AlbumId });
    }

    public ActionResult Delete(int id)
    {
      Album thisAlbum = _db.Albums.FirstOrDefault(album => album.AlbumId == id);
      return View (thisAlbum);
    }

    [HttpPost, ActionName("Delete")]
    public ActionResult DeleteConfirmed(int id)
    {
      Album thisAlbum = _db.Albums.FirstOrDefault(album => album.AlbumId == id);
      _db.Albums.Remove(thisAlbum);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }
    public ActionResult AddArtist(int id)
    {
      Album model = _db.Albums.FirstOrDefault(album => album.AlbumId == id);
      ViewBag.ArtistId = new SelectList(_db.Artists, "ArtistId", "Name");
      return View(model);
    }
    
    [HttpPost]
    public ActionResult AddArtist(Album album, int artistId)
    {
      _db.AlbumArtistGenre.Add(new AlbumArtistGenre(){AlbumId = album.AlbumId, ArtistId = artistId});
      _db.SaveChanges();
      return RedirectToAction("Details", new {id = album.AlbumId});
    }
    
    public ActionResult AddGenre(int id)
    {
      Album model = _db.Albums.FirstOrDefault(album => album.AlbumId == id);
      ViewBag.GenreId = new SelectList(_db.Genres, "GenreId", "Name");
      return View(model);
    }
    
    [HttpPost]
    public ActionResult AddGenre(Album album, int genreId)
    {
      _db.AlbumArtistGenre.Add(new AlbumArtistGenre(){AlbumId = album.AlbumId, GenreId = genreId});
      _db.SaveChanges();
      return RedirectToAction("Details", new {id = album.AlbumId});
    }
  }
}

RecordCollection/Controllers/ArtistsController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using System.Collections.Generic;
using System.Linq;
using System.Text.RegularExpressions;
using RecordCollection.Models;

namespace RecordCollection.Controllers
{
  public class ArtistsController : Controller
  {
    private readonly RecordCollectionContext _db;

    public ArtistsController(RecordCollectionContext db)
    {
      _db = db;
    }

    public ActionResult Index(string name)
    {
      IQueryable<Artist> artistQuery = _db.Artists;
      if (!string.IsNullOrEmpty(name))
      {
        Regex search = new Regex(name, RegexOptions.IgnoreCase);
        artistQuery = artistQuery.Where(artists => search.IsMatch(artists.Name));
      }
      IEnumerable<Artist> artistList = artistQuery.ToList().OrderBy(artists => artists.Name);
      return View(artistList);
    }

    public ActionResult Create()
    {
      ViewBag.AlbumId = new SelectList(_db.Albums, "AlbumId", "Name");
      ViewBag.GenreId = new SelectList(_db.Genres, "GenreId", "Name");
      return View();
    }

    [HttpPost]
    public ActionResult Create(Artist artist, int AlbumId, int GenreId)
    {
      _db.Artists.Add(artist);
      if (AlbumId != 0)
      {
        _db.AlbumArtistGenre.Add(new AlbumArtistGenre() { AlbumId = AlbumId, ArtistId = artist.ArtistId });
      }
      if (GenreId != 0)
      {
        _db.AlbumArtistGenre.Add(new AlbumArtistGenre() { GenreId = GenreId, ArtistId = artist.ArtistId });
      }
      _db.SaveChanges();
      return RedirectToAction("Details", new { id = artist.ArtistId });
    }

    public ActionResult Details(int id)
    {
      Artist artist = _db.Artists
        .Include(artists => artists.AlbumsGenres)
        .ThenInclude(join => join.Album)
        .Include(artists => artists.AlbumsGenres)
        .ThenInclude(join => join.Genre)
        .FirstOrDefault(artists => artists.ArtistId == id);
      ViewBag.AlbumCount = _db.AlbumArtistGenre.Where(join => join.ArtistId == id).Where(join => join.AlbumId != null).Count();
      ViewBag.GenreCount = _db.AlbumArtistGenre.Where(join => join.ArtistId == id).Where(join => join.GenreId != null).Count();
      return View(artist);
    }

    public ActionResult Edit(int id)
    {
      Artist artist = _db.Artists.FirstOrDefault(artists => artists.ArtistId == id);
      return View(artist);
    }

    [HttpPost]
    public ActionResult Edit(Artist artist)
    {
      _db.Entry(artist).State = EntityState.Modified;
      _db.SaveChanges();
      return RedirectToAction("Details", new { id = artist.ArtistId });
    }

    public ActionResult Delete(int id)
    {
      Artist artist = _db.Artists.FirstOrDefault(artists => artists.ArtistId == id);
      return View(artist);
    }

    [HttpPost, ActionName("Delete")]
    public ActionResult DeleteConfirmed(int id)
    {
      Artist artist = _db.Artists.FirstOrDefault(artists => artists.ArtistId == id);
      _db.Artists.Remove(artist);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    public ActionResult AddAlbum(int id)
    {
      Artist artist = _db.Artists.FirstOrDefault(artists => artists.ArtistId == id);
      ViewBag.AlbumId = new SelectList(_db.Albums, "AlbumId", "Name");
      return View(artist);
    }

    [HttpPost]
    public ActionResult AddAlbum(Artist artist, int AlbumId)
    {
      _db.AlbumArtistGenre.Add(new AlbumArtistGenre(){ AlbumId = AlbumId, ArtistId = artist.ArtistId });
      _db.SaveChanges();
      return RedirectToAction("Details", new { id = artist.ArtistId });
    }

    public ActionResult AddGenre(int id)
    {
      Artist artist = _db.Artists.FirstOrDefault(artists => artists.ArtistId == id);
      ViewBag.GenreId = new SelectList(_db.Genres, "GenreId", "Name");
      return View(artist);
    }

    [HttpPost]
    public ActionResult AddGenre(Artist artist, int GenreId)
    {
      _db.AlbumArtistGenre.Add(new AlbumArtistGenre(){ GenreId = GenreId, ArtistId = artist.ArtistId });
      _db.SaveChanges();
      return RedirectToAction("Details", new { id = artist.ArtistId });
    }
  }
}

RecordCollection/Controllers/GenresController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using System.Collections.Generic;
using System.Linq;
using System.Text.RegularExpressions;
using RecordCollection.Models;

namespace RecordCollection.Controllers
{
  public class GenresController : Controller
  {
    private readonly RecordCollectionContext _db;

    public GenresController(RecordCollectionContext db)
    {
      _db = db;
    }

    public ActionResult Index(string name)
    {
      IQueryable<Genre> genreQuery = _db.Genres;
      if (!string.IsNullOrEmpty(name))
      {
        Regex search = new Regex(name, RegexOptions.IgnoreCase);
        genreQuery = genreQuery.Where(genres => search.IsMatch(genres.Name));
      }
      IEnumerable<Genre> genreList = genreQuery.ToList().OrderBy(genres =>genres.Name);
      return View(genreList);
    }

    public ActionResult Create()
    {
      ViewBag.AlbumId = new SelectList(_db.Albums, "AlbumId", "Name");
      ViewBag.ArtistId = new SelectList(_db.Artists, "ArtistId", "Name");
      return View();
    }

    [HttpPost]
    public ActionResult Create(Genre genre, int AlbumId, int ArtistId)
    {
      _db.Genres.Add(genre);
      if (AlbumId != 0)
      {
        _db.AlbumArtistGenre.Add(new AlbumArtistGenre() { AlbumId = AlbumId, GenreId = genre.GenreId });
      }
      if (ArtistId != 0)
      {
        _db.AlbumArtistGenre.Add(new AlbumArtistGenre() { ArtistId = ArtistId, GenreId = genre.GenreId });
      }
      _db.SaveChanges();
      return RedirectToAction("Details", new { id = genre.GenreId });
    }

    public ActionResult Details(int id)
    {
      Genre genre = _db.Genres
        .Include(genres => genres.AlbumsArtists)
        .ThenInclude(join => join.Album)
        .Include(genres => genres.AlbumsArtists)
        .ThenInclude(join => join.Artist)
        .FirstOrDefault(genres => genres.GenreId == id);
      ViewBag.AlbumCount = _db.AlbumArtistGenre.Where(join => join.GenreId == id).Where(join => join.AlbumId != null).Count();
      ViewBag.ArtistCount = _db.AlbumArtistGenre.Where(join => join.GenreId == id).Where(join => join.ArtistId != null).Count();
      return View(genre);
    }

    public ActionResult Edit(int id)
    {
      Genre genre = _db.Genres.FirstOrDefault(genres => genres.GenreId == id);
      return View(genre);
    }

    [HttpPost]
    public ActionResult Edit(Genre genre)
    {
      _db.Entry(genre).State = EntityState.Modified;
      _db.SaveChanges();
      return RedirectToAction("Details", new { id = genre.GenreId });
    }

    public ActionResult Delete(int id)
    {
      Genre genre = _db.Genres.FirstOrDefault(genres => genres.GenreId == id);
      return View(genre);
    }

    [HttpPost, ActionName("Delete")]
    public ActionResult DeleteConfirmed(int id)
    {
      Genre genre = _db.Genres.FirstOrDefault(genres => genres.GenreId == id);
      _db.Genres.Remove(genre);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    public ActionResult AddAlbum(int id)
    {
      Genre genre = _db.Genres.FirstOrDefault(genres => genres.GenreId == id);
      ViewBag.AlbumId = new SelectList(_db.Albums, "AlbumId", "Name");
      return View(genre);
    }

    [HttpPost]
    public ActionResult AddAlbum(Genre genre, int AlbumId)
    {
      _db.AlbumArtistGenre.Add(new AlbumArtistGenre(){ AlbumId = AlbumId, GenreId = genre.GenreId });
      _db.SaveChanges();
      return RedirectToAction("Details", new { id = genre.GenreId });
    }

    public ActionResult AddArtist(int id)
    {
      Genre genre = _db.Genres.FirstOrDefault(genres => genres.GenreId == id);
      ViewBag.ArtistId = new SelectList(_db.Artists, "ArtistId", "Name");
      return View(genre);
    }

    [HttpPost]
    public ActionResult AddArtist(Genre genre, int ArtistId)
    {
      _db.AlbumArtistGenre.Add(new AlbumArtistGenre(){ ArtistId = ArtistId, GenreId = genre.GenreId });
      _db.SaveChanges();
      return RedirectToAction("Details", new { id = genre.GenreId });
    }
  }
}

RecordCollection/Views/Artists/AddAlbum.cshtml
@{
  Layout = "_Layout";
}

@model RecordCollection.Models.Artist

<h2>Add Album to @Html.DisplayFor(model => model.Name)</h2>

@using (Html.BeginForm())
{
  @Html.HiddenFor(model => model.ArtistId)

  @Html.Label("Select Album:")
  @Html.DropDownList("AlbumId")

  <input type="submit" value="Add Album" />
}

<p>@Html.ActionLink("Back Without Saving", "Details", new { id = Model.ArtistId })</p>
<p>@Html.ActionLink("Add Genre", "AddGenre", new { id = Model.ArtistId })</p>
<p>@Html.ActionLink("Album List", "Index")</p>
<p>@Html.ActionLink("Home", "Index", "Home")</p>

RecordCollection/Views/Artists/AddGenre.cshtml
@{
  Layout = "_Layout";
}

@model RecordCollection.Models.Artist

<h2>Add Genre to @Html.DisplayFor(model => model.Name)</h2>

@using (Html.BeginForm())
{
  @Html.HiddenFor(model => model.ArtistId)

  @Html.Label("Select Genre:")
  @Html.DropDownList("GenreId")

  <input type="submit" value="Add Genre" />
}

<p>@Html.ActionLink("Back Without Saving", "Details", new { id = Model.ArtistId })</p>
<p>@Html.ActionLink("Add Album", "AddAlbum", new { id = Model.ArtistId })</p>
<p>@Html.ActionLink("Artist List", "Index")</p>
<p>@Html.ActionLink("Home", "Index", "Home")</p>

RecordCollection/Views/Artists/Create.cshtml
@{
  Layout = "_Layout";
}

@model RecordCollection.Models.Artist

<h2>Add Artist</h2>

@using (Html.BeginForm())
{
  @Html.LabelFor(model => model.Name)
  @Html.TextBoxFor(model => model.Name)

  @Html.Label("Url For a Pic:")
  @Html.TextBoxFor(model => model.ImageUrl)

  @Html.Label("Add an Album To This Artist: ")
  @Html.DropDownList("AlbumId", (SelectList)ViewBag.AlbumId, " ")

  @Html.Label("Add a Genre To This Artist: ")
  @Html.DropDownList("GenreId", (SelectList)ViewBag.GenreId, " ")

  <input type="submit" value="Add Artist" />
}

<p>@Html.ActionLink("Artist List", "Index")</p>
<p>@Html.ActionLink("Home", "Index", "Home")</p>

RecordCollection/Views/Artists/Delete.cshtml
@{
  Layout = "_Layout";
}

@model RecordCollection.Models.Artist

<h3>Are you sure you want to delete @Html.DisplayFor(model => model.Name)?</h3>

@using (Html.BeginForm())
{
  <input type="submit" value="Confirm Delete" />
}

<p>@Html.ActionLink("Back Without Deleting", "Details", new { id = Model.ArtistId })</p>
<p>@Html.ActionLink("Artist List", "Index")</p>
<p>@Html.ActionLink("Home", "Index", "Home")</p>

RecordCollection/Views/Artists/Details.cshtml
@{
  Layout = "_Layout";
}

@using RecordCollection.Models;
@model RecordCollection.Models.Artist;

<h2>Artist Details</h2>
<hr />
<h3>@Html.DisplayNameFor(model => model.Name): @Html.DisplayFor(model => model.Name)</h3>

@if(Model.ImageUrl != null)
{
  <img src="@Model.ImageUrl" />
}

@if(ViewBag.AlbumCount == 0)
{
  <p>There are no albums associated with this artist.</p>
}
else
{
  <h4>Albums:</h4>
  <ul>
  @foreach(AlbumArtistGenre join in Model.AlbumsGenres)
  {
    @if (join.AlbumId != null)
    {
      <li>@Html.ActionLink($"{join.Album.Name}", "Details", "Albums", new { id = @join.Album.AlbumId})</li>
    }
  }
  </ul>
}

@if(ViewBag.GenreCount == 0)
{
  <p>There are no genres associated with this artist.</p>
}
else
{
  <h4>Genres:</h4>
  <ul>
  @foreach(AlbumArtistGenre join in Model.AlbumsGenres)
  {
    @if (join.GenreId != null)
    {
      <li>@Html.ActionLink($"{join.Genre.Name}", "Details", "Genres", new { id = @join.Genre.GenreId})</li>
    }
  }
  </ul>
}

<p>@Html.ActionLink("Back to Artists", "Index")</p>
<p>@Html.ActionLink("Edit Artist", "Edit", new { id = Model.ArtistId })</p>
<p>@Html.ActionLink("Delete Artist", "Delete", new { id = Model.ArtistId })</p>
<p>@Html.ActionLink("Add Album", "AddAlbum", new { id = Model.ArtistId })</p>
<p>@Html.ActionLink("Add Genre", "AddGenre", new { id = Model.ArtistId })</p>

RecordCollection/Views/Artists/Edit.cshtml
@{
  Layout = "_Layout";
}

@model RecordCollection.Models.Artist

<h2>Edit @Html.DisplayFor(model => model.Name)</h2>

@using (Html.BeginForm())
{
  @Html.HiddenFor(model => model.ArtistId)

  @Html.LabelFor(model => model.Name)
  @Html.TextBoxFor(model => model.Name)

  @Html.Label("Url for a Pic:")
  @Html.TextBoxFor(model => model.ImageUrl)

  <input type="submit" value="Save" />
}

<p>@Html.ActionLink("Back Without Saving", "Details", new { id = Model.ArtistId })</p>
<p>@Html.ActionLink("Artist List", "Index")</p>
<p>@Html.ActionLink("Home", "Index", "Home")</p>

RecordCollection/Views/Artists/Index.cshtml
@{
  Layout = "_Layout";
}

@using RecordCollection.Models;
@model IEnumerable<RecordCollection.Models.Artist>;

@if (Model.Count() == 0)
{
  <p>There are no Artists to display, please add an artist.</p>
}

<ul>
@foreach(Artist artist in Model)
{
  <li>@Html.ActionLink($"{artist.Name}", "Details", new {id = artist.ArtistId})</li>
}
</ul>

<p>@Html.ActionLink("Add new artist", "Create")</p>
<p>@Html.ActionLink("Home", "Index", "Home")</p>